language: ruby
bundler_args: --without tool
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  - rbx
gemfile:
  - gemfiles/Gemfile.rspec-2.14
  - gemfiles/Gemfile.rspec-3.0
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx
notifications:
  recipients:
    - thibaud@thibaud.gg
